### ISSUE TITLE
IE10/11 solutions seem to cause several side-effects

### ISSUE THREAD

**Issue by gkatsanos** [philipwalton/solved-by-flexbox#96]
I have been trying to make `height: 100%` work for quite some time now - unfortunately - too many problems, especially if content is more than the visible fold. 

Compared your use case with mine, tried to simplify the layout by removing as many elements in the main content area as possible, nothing seems to work.

Ended up using 

```css
@media all and (-ms-high-contrast: none), (-ms-high-contrast: active) {
  // IE10+ only styles here. 
  .main-content { min-height: 75vh; } 
}
```

it's definitely not great, but it's better than the footer jumping in the middle of the screen.. and `height: 100%` adds way too many side-effects for it to be a viable solution.
